#!/usr/bin/env Rscript
# Figure 7 — Panel A: Top-12 per-module ROCs (ranked by permutation p)
#
# Reads : 04_Figures/F07/c_data/module_grid/module_grid_{summary,curves}.csv
#         (generated by _supp_module_grid.R — must run that first)
# Writes: 04_Figures/F07/b_reports/main/{png,pdf}/panels/MAIN_panel_A_auc.{png,pdf}
#
# Sourced by 01_main_panels.R — expects style.R + figure_supplement_helpers.R
# already loaded.
# Exports: pA, pA_title, pA_subtitle, pA_legend

suppressPackageStartupMessages({
  library(tidyverse); library(patchwork)
})

BASE    <- "04_Figures/F07"
DAT     <- file.path(BASE, "c_data", "module_grid")
RPT_PNG <- file.path(BASE, "b_reports", "main", "png", "panels")
RPT_PDF <- file.path(BASE, "b_reports", "main", "pdf", "panels")
dir.create(RPT_PNG, recursive = TRUE, showWarnings = FALSE)
dir.create(RPT_PDF, recursive = TRUE, showWarnings = FALSE)

summ_all   <- read_csv(file.path(DAT, "module_grid_summary.csv"), show_col_types = FALSE)
curves_all <- read_csv(file.path(DAT, "module_grid_curves.csv"),  show_col_types = FALSE)

# Pathway labels for color key
F06_SUPP <- "04_Figures/F06/c_data/F06_supplementary.xlsx"
stopifnot("F06 stitcher must run first: missing F06_supplementary.xlsx" =
  file.exists(F06_SUPP))
mod_bio_df <- read_sheet_df(F06_SUPP, "WGCNA_mod_bio_labels")
mod_bio    <- setNames(mod_bio_df$bio_label, mod_bio_df$module_color)

# Select top 12 by perm_p
top12 <- summ_all |>
  arrange(perm_p, desc(auc)) |>
  slice_head(n = 12) |>
  mutate(rank = row_number(),
         row_idx = ((rank - 1) %/% 6) + 1L,   # 2 rows
         col_idx = ((rank - 1) %%  6) + 1L,   # 6 cols
         sig = case_when(q_bh < 0.05   ~ "q<.05",
                         perm_p < 0.05 ~ "p<.05",
                         TRUE          ~ "ns"),
         border_color = ifelse(sig == "ns", "grey80", "black"),
         border_lty   = ifelse(sig == "p<.05", "dashed", "solid"),
         border_lw    = case_when(sig == "q<.05" ~ 0.8,
                                  sig == "p<.05" ~ 0.8,
                                  TRUE           ~ 0.2),
         pretty_outcome = recode(row,
           "Age"                 = "Age (Y vs O)",
           "\u0394VL-responder"  = "\u0394 VL resp.",
           "Pre vs Post"         = "Pre\u2192Post (all)",
           "Pre vs Post (Young)" = "Pre\u2192Post (Y)",
           "Pre vs Post (Old)"   = "Pre\u2192Post (O)",
           "LBM (High vs Low)"   = "Baseline LBM"))

# Cell builder
build_cell <- function(i) {
  rr <- top12[i, ]
  dd <- curves_all |> filter(row == rr$row, module == rr$module)
  col <- rr$module
  show_x <- rr$row_idx == 2L   # bottom row (2-row layout)
  show_y <- rr$col_idx == 1L   # left column

  auc_line <- sprintf("AUC %.2f", rr$auc)
  ci_line  <- sprintf("[%.2f, %.2f]", rr$ci_lo, rr$ci_hi)
  p_line   <- if (rr$perm_p < 0.001) "p < .001" else sprintf("p = %.3f", rr$perm_p)
  q_line   <- if (is.na(rr$q_bh)) "q = NA" else if (rr$q_bh < 0.001) "q < .001" else sprintf("q = %.3f", rr$q_bh)
  ctx_line <- rr$pretty_outcome

  g <- ggplot(dd, aes(fpr, tpr)) +
    geom_ribbon(aes(ymin = 0, ymax = tpr), fill = col, alpha = 0.32) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed",
                color = "grey70", linewidth = 0.3) +
    geom_line(color = col, linewidth = 1.1) +
    annotate("label", x = 0.69, y = 0.45,
             label = paste(auc_line, ci_line, p_line, q_line, sep = "\n"),
             hjust = 0.5, vjust = 0.5, size = 2.0, fontface = "bold",
             color = "grey5", fill = "white",
             linewidth = 0.2, label.padding = unit(3, "pt"),
             label.r = unit(3, "pt")) +
    # Context title centered at bottom of plot (inside, with white background)
    annotate("label", x = 0.50, y = 0.03, label = ctx_line,
             hjust = 0.5, vjust = 0, size = 3.1, fontface = "bold.italic",
             color = "grey15", fill = scales::alpha("white", 0.82),
             linewidth = 0, label.padding = unit(1.5, "pt"),
             label.r = unit(3, "pt")) +
    scale_x_continuous(limits = c(0,1),
                       breaks = c(0, 1), labels = c("0", "1"),
                       expand = c(0,0)) +
    scale_y_continuous(limits = c(0,1),
                       breaks = c(0, 1), labels = c("0", "1"),
                       expand = c(0,0)) +
    coord_cartesian(clip = "off") +
    labs(x = if (show_x) "1 \u2212 Specificity" else NULL,
         y = if (show_y) "Sensitivity"     else NULL) +
    theme_classic(base_size = 15) +
    theme(panel.border = element_rect(fill = NA,
                                      color = rr$border_color,
                                      linewidth = rr$border_lw,
                                      linetype = rr$border_lty),
          axis.title.x = element_text(size = 5, face = "bold",
                                      color = "grey25",
                                      margin = margin(t = -2)),
          axis.title.y = element_text(size = 5, face = "bold",
                                      color = "grey25",
                                      margin = margin(r = -2)),
          axis.text.x  = if (show_x) element_text(size = FIG_AXIS_TEXT, color = "grey30")
                         else element_blank(),
          axis.text.y  = if (show_y) element_text(size = FIG_AXIS_TEXT, color = "grey30")
                         else element_blank(),
          axis.ticks   = element_line(color = "grey40", linewidth = 0.3),
          axis.line    = element_blank(),
          plot.margin = margin(0, 0, 8, 0))  # bottom margin for context title
  g
}

cells <- lapply(seq_len(nrow(top12)), build_cell)
grid12 <- wrap_plots(cells, nrow = 2, ncol = 6) &
  theme(plot.margin = margin(0, 0, 8, 0))

# Pathway color key (bottom strip)
MODULES_KEY <- c("turquoise","blue","brown",
                 "green","red","black")
key_df <- tibble(
  module  = MODULES_KEY,
  label   = unname(mod_bio[MODULES_KEY]),
  x_pos   = seq_along(MODULES_KEY))

build_key_cell <- function(mod, lab) {
  ggplot() +
    annotate("rect", xmin = 0.02, xmax = 0.09, ymin = 0.22, ymax = 0.78,
             fill = mod, color = "grey20", linewidth = 0.4) +
    annotate("text", x = 0.11, y = 0.5,
             label = paste0(stringr::str_to_title(mod), " \u2014 ", lab),
             hjust = 0, vjust = 0.5, size = 2.6, color = "grey10") +
    scale_x_continuous(limits = c(0,1), expand = c(0,0)) +
    scale_y_continuous(limits = c(0,1), expand = c(0,0)) +
    coord_cartesian(clip = "off") +
    theme_void() +
    theme(plot.margin = margin(5, 1, 5, 1))
}

key_cells <- purrr::map2(key_df$module, key_df$label, build_key_cell)
key_composite <- wrap_plots(key_cells, nrow = 2, ncol = 3)

# Assemble
composite <- grid12 / key_composite +
  plot_layout(heights = c(11, 1.5))

composite <- composite +
  plot_annotation(
    title    = "Top 12 per-module ROCs ranked by permutation p",
    subtitle = "Univariate module eigengene \u2192 outcome. Border: thick solid black = BH q<0.05, thick dashed black = nominal p<0.05.",
    theme = theme(
      plot.title    = element_text(face = "bold", size = FIG_TITLE_SIZE, color = "grey10",
                                   margin = margin(b = 1, l = 30)),
      plot.subtitle = element_text(size = FIG_SUBTITLE_SIZE, face = "italic", color = "grey30",
                                   margin = margin(b = 4, l = 30))))

W_mm <- 210; H_mm <- 75
ggsave(file.path(RPT_PNG, "MAIN_panel_A_auc.png"), composite,
       width = W_mm, height = H_mm, units = "mm", dpi = 300)
ggsave(file.path(RPT_PDF, "MAIN_panel_A_auc.pdf"), composite,
       width = W_mm, height = H_mm, units = "mm",
       device = get_pdf_device())

message("Wrote: MAIN_panel_A_auc.{png,pdf}")

# Export for composite
pA_title    <- "Top 12 per-module ROCs ranked by permutation p"
pA_subtitle <- "Univariate module eigengene \u2192 outcome. Border: thick solid black = BH q<0.05, thick dashed black = nominal p<0.05."
pA_legend   <- NULL   # module key stays embedded in patchwork layout
pA          <- composite +
  plot_annotation(title = NULL, subtitle = NULL)
