#!/usr/bin/env Rscript
# Figure 6 — Panels A and B: per-module ROCs, split by what they classify
#
# Reads : 04_Figures/F06/c_data/module_grid/module_grid_{summary,curves}.csv
#         (generated by _supp_module_grid.R — must run that first)
# Writes: 04_Figures/F06/b_reports/main/{png,pdf}/panels/
#         MAIN_panel_A_age_roc.{png,pdf}, MAIN_panel_B_training_roc.{png,pdf}
#
# Sourced by 01_main_panels.R — expects style.R + figure_supplement_helpers.R
# already loaded.
# Exports: pA, pA_title, pA_subtitle, pA_legend,
#          pB, pB_title, pB_subtitle, pB_legend

pacman::p_load(tidyverse, patchwork)

source("04_Figures/F06/a_script/_panel_selection.R")

BASE <- "04_Figures/F06"
DAT <- file.path(BASE, "c_data", "module_grid")
RPT_PNG <- file.path(BASE, "b_reports", "main", "png", "panels")
RPT_PDF <- file.path(BASE, "b_reports", "main", "pdf", "panels")
dir.create(RPT_PNG, recursive = TRUE, showWarnings = FALSE)
dir.create(RPT_PDF, recursive = TRUE, showWarnings = FALSE)

summ_all <- read_csv(file.path(DAT, "module_grid_summary.csv"), show_col_types = FALSE)
curves_all <- read_csv(file.path(DAT, "module_grid_curves.csv"), show_col_types = FALSE)

F05_SUPP <- "04_Figures/F05/c_data/F05_supplementary.xlsx"
stopifnot(
  "F05 stitcher must run first: missing F05_supplementary.xlsx" =
    file.exists(F05_SUPP)
)
mod_bio_df <- read_sheet_df(F05_SUPP, "WGCNA_mod_bio_labels")
# display_label is the canonical "Turquoise: Beta Ox. | TCA" string every
# other figure prints. Re-deriving colour + separator + bio_label here is how
# F05 and F06 drift apart on the same module.
mod_display <- setNames(mod_bio_df$display_label, mod_bio_df$module_color)

# Two panels, two questions. The grid used to rank all 48 (comparison x
# module) cells together and draw the top twelve, which put six different
# comparisons in one panel and made every cell carry a caption saying which it
# was. Split by comparison, each panel makes one statement.
cells_df <- main_panel_cells(summ_all)

age_cells <- cells_df |> filter(panel == "age")
train_cells <- cells_df |> filter(panel == "training")

GRID_NCOL <- 3L

build_cell <- function(rr, i, n) {
  dd <- curves_all |> filter(row == rr$row, module == rr$module)
  col <- module_fill(rr$module)
  show_x <- i > n - GRID_NCOL # bottom row, whatever the row count is
  show_y <- ((i - 1L) %% GRID_NCOL) == 0L # left column

  auc_line <- sprintf("AUC %.2f", rr$auc)
  ci_line <- sprintf("[%.2f, %.2f]", rr$ci_lo, rr$ci_hi)
  p_line <- if (rr$perm_p < 0.001) "p < .001" else sprintf("p = %.3f", rr$perm_p)
  q_line <- if (is.na(rr$q_bh)) "q = NA" else if (rr$q_bh < 0.001) "q < .001" else sprintf("q = %.3f", rr$q_bh)
  ctx_line <- rr$cell_label

  g <- ggplot(dd, aes(fpr, tpr)) +
    geom_ribbon(aes(ymin = 0, ymax = tpr), fill = col, alpha = 0.32) +
    geom_abline(
      slope = 1, intercept = 0, linetype = "dashed",
      color = "grey70", linewidth = 0.3
    ) +
    geom_line(color = col, linewidth = 1.1) +
    annotate("label",
      x = 0.69, y = 0.45,
      label = paste(auc_line, ci_line, p_line, q_line, sep = "\n"),
      hjust = 0.5, vjust = 0.5, size = 2.0, fontface = "bold",
      color = "grey5", fill = "white",
      linewidth = 0.2, label.padding = unit(3, "pt"),
      label.r = unit(3, "pt")
    ) +
    # Context title centered at bottom of plot (inside, with white background)
    annotate("label",
      x = 0.50, y = 0.03, label = ctx_line,
      hjust = 0.5, vjust = 0, size = 3.1, fontface = "bold.italic",
      color = "grey15", fill = scales::alpha("white", 0.82),
      linewidth = 0, label.padding = unit(1.5, "pt"),
      label.r = unit(3, "pt")
    ) +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = c(0, 1), labels = c("0", "1"),
      expand = c(0, 0)
    ) +
    scale_y_continuous(
      limits = c(0, 1),
      breaks = c(0, 1), labels = c("0", "1"),
      expand = c(0, 0)
    ) +
    coord_cartesian(clip = "off") +
    labs(
      x = if (show_x) "1 \u2212 Specificity" else NULL,
      y = if (show_y) "Sensitivity" else NULL
    ) +
    theme_classic(base_size = 15) +
    theme(
      panel.border = element_rect(
        fill = NA,
        color = rr$border_color,
        linewidth = rr$border_lw,
        linetype = rr$border_lty
      ),
      axis.title.x = element_text(
        size = 5, face = "bold",
        color = "grey25",
        margin = margin(t = -2)
      ),
      axis.title.y = element_text(
        size = 5, face = "bold",
        color = "grey25",
        margin = margin(r = -2)
      ),
      axis.text.x = if (show_x) {
        element_text(size = FIG_AXIS_TEXT, color = "grey30")
      } else {
        element_blank()
      },
      axis.text.y = if (show_y) {
        element_text(size = FIG_AXIS_TEXT, color = "grey30")
      } else {
        element_blank()
      },
      axis.ticks = element_line(color = "grey40", linewidth = 0.3),
      axis.line = element_blank(),
      plot.margin = margin(0, 0, 8, 0)
    ) # bottom margin for context title
  g
}

build_grid <- function(df) {
  n <- nrow(df)
  cells <- lapply(seq_len(n), function(i) build_cell(df[i, ], i, n))
  wrap_plots(cells, ncol = GRID_NCOL) &
    theme(plot.margin = margin(0, 0, 8, 0))
}

grid_age <- build_grid(age_cells)
grid_train <- build_grid(train_cells)

# One key for both panels, listing every module either of them draws, in
# canonical order. Data-driven, so it can neither show a module that is absent
# nor omit one that is present.
MODULES_KEY <- intersect(names(mod_display), unique(cells_df$module))
key_df <- tibble(
  module = MODULES_KEY,
  label = unname(mod_display[MODULES_KEY])
)

build_key_cell <- function(mod, lab) {
  ggplot() +
    annotate("rect",
      xmin = 0.02, xmax = 0.09, ymin = 0.22, ymax = 0.78,
      fill = module_fill(mod), color = "grey20", linewidth = 0.4
    ) +
    annotate("text",
      x = 0.11, y = 0.5, label = lab,
      hjust = 0, vjust = 0.5, size = 2.6, color = "grey10"
    ) +
    scale_x_continuous(limits = c(0, 1), expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) +
    coord_cartesian(clip = "off") +
    theme_void() +
    theme(plot.margin = margin(5, 1, 5, 1))
}

key_cells <- purrr::map2(key_df$module, key_df$label, build_key_cell)
# Two rows of three across the full canvas. Six across left each label 35 mm
# and cut "Turquoise: Beta Ox. | TCA" short; three across gives it 70 mm.
key_composite <- wrap_plots(key_cells, nrow = 2, ncol = 3)

# Both grids are half the 210 mm canvas and the same height, so the size is
# the function's, not the caller's.
save_panel <- function(plot, stem) {
  ggsave(file.path(RPT_PNG, paste0(stem, ".png")), plot,
    width = 105, height = 62, units = "mm", dpi = 300
  )
  ggsave(file.path(RPT_PDF, paste0(stem, ".pdf")), plot,
    width = 105, height = 62, units = "mm", device = get_pdf_device()
  )
}

save_panel(grid_age, "MAIN_panel_A_age_roc")
save_panel(grid_train, "MAIN_panel_B_training_roc")

message("  MAIN panels A and B saved (age and training ROC grids)")

# Every cell in both panels already exists in module_grid_summary; the split
# changes which are drawn, not what was computed. Two cells that used to reach
# the top-twelve slice belong to neither question -- Pre vs Post pooled across
# ages, and the DeltaVL responder split -- so the subtitle says where they went
# rather than letting a BH-significant cell disappear without comment.
# One line each, measured against the 93 mm a half-canvas panel allows. The
# panel C subtitle clipped at 99% of its budget, so these sit near 80%.
pA_title <- "Modules that separate younger from older"
pA_subtitle <- "Mean Pre/Post ME | q<.05 solid, p<.05 dashed"
pA_legend <- NULL
pA <- grid_age + plot_annotation(title = NULL, subtitle = NULL)

pB_title <- "Modules that separate pre from post training"
# Which row is which is not stated: every cell already says "Blue . Younger"
# or "Blue . Older", so a line repeating it is ink for nothing.
pB_subtitle <- "No older module reaches p<.05 | rest in S7 Figure"
pB_legend <- NULL
pB <- grid_train + plot_annotation(title = NULL, subtitle = NULL)

# The key serves both panels, so it spans the canvas rather than sitting under
# one of them -- inside a half-width panel its labels were truncated.
pKey <- key_composite
